### ISSUE TITLE
[Bug] SyntaxError when NodeJS v12 is used 

### ISSUE THREAD

**Issue by cybertron10** [lauritzh/domscan#22]
hacker@ubuntu:~/domscan$ node scan.js 
/home/hacker/domscan/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:128
        return this.eventsMap.get(event)?.length || 0;
                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hacker/domscan/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Browser.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by lauritzh** [comment]
Hi there!

Thanks a lot for reaching out :)
Could you please provide further information about your environment? Which Ubuntu and Node versions do you use?


Best regards,

Lauritz

**Comment by cybertron10** [comment]
![image](https://github.com/lauritzh/domscan/assets/56225601/ebf246df-23ce-4dfa-a726-73a884745898)

**Comment by lauritzh** [comment]
Could you please try whether the tool works with NodeJS v20 for you?
I also updated the dependencies so that there should be an error on installation if you use older versions of Node and NPM.

**Comment by lauritzh** [comment]
I am going ahead and close this issue, as it was not reproducible on recent NodeJS versions. Please let me know in case you are still facing any issues.
