### ISSUE TITLE
Failed to launch the browser process! undefined

### ISSUE THREAD

**Issue by abdulx01** [lauritzh/domscan#57]
How to solve this issue, when I run this tool this give a error:
```bash
[!] No URL or hash parameters found. If you do not intent to only guess parameters (see help), please provide an URL that already includes GET parameters.
[+] Adding mutations of given URL parameter values to payload list...
[+] Starting browser...
Failed to launch the browser process! undefined
[1194:1194:1001/000912.154161:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting
: Error: Failed to launch the browser process! undefined
[1194:1194:1001/000912.154161:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/local/lib/node_modules/domscan/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

```
What's solution ?

**Comment by lauritzh** [comment]
Hi @abdulx01,

thank you very much for testing domscan! :) 

With v.0.0.5 (recent release from last week) @chouaibhm contributed a `--no-sandbox` flag which should resolve this issue: https://github.com/lauritzh/domscan/pull/51 

**Could your please try whether this option resolves your error?**


Best regards and have a great day,

Lauritz

**Comment by abdulx01** [comment]
Same issue with `--no-sandbox` flag.
```bash
root@AbdulRahman ~/R/domscan (main)# domscan -g -G https://portswigger-labs.net/dom-invader/testcases/augmented-dom-document-write/ --no-sandbox

     _
  __| | ___  _ __ ___  ___  ___ __ _ _ __
 / _` |/ _ \| '_ ` _ \/ __|/ __/ _` | '_ \
| (_| | (_) | | | | | \__ \ (_| (_| | | | |
 \__,_|\___/|_| |_| |_|___/\___\__,_|_| |_|

 (C) Lauritz Holtmann, 2023

[+] URL: https://portswigger-labs.net/dom-invader/testcases/augmented-dom-document-write/
[!] No URL or hash parameters found. If you do not intent to only guess parameters (see help), please provide an URL that already includes GET parameters.
[+] Adding mutations of given URL parameter values to payload list...
[+] Starting browser...
Failed to launch the browser process! undefined
[1441:1441:1006/002207.388918:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting
: Error: Failed to launch the browser process! undefined
[1441:1441:1006/002207.388918:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/local/lib/node_modules/domscan/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    ```

Example2:
```bash

└─# domscan -g -G https://0a6a00e504d145158496868700cb008f.web-security-academy.net/?search=hello --no-sandbox

     _
  __| | ___  _ __ ___  ___  ___ __ _ _ __
 / _` |/ _ \| '_ ` _ \/ __|/ __/ _` | '_ \
| (_| | (_) | | | | | \__ \ (_| (_| | | | |
 \__,_|\___/|_| |_| |_|___/\___\__,_|_| |_|

 (C) Lauritz Holtmann, 2023

[+] URL: https://0a6a00e504d145158496868700cb008f.web-security-academy.net/?search=hello
[+] URL Parameters: {"search":"hello"}
[+] Adding mutations of given URL parameter values to payload list...
[+] Starting browser...
Failed to launch the browser process! undefined
[1495:1495:1006/002757.884967:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting
: Error: Failed to launch the browser process! undefined
[1495:1495:1006/002757.884967:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/local/lib/node_modules/domscan/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```
My other headless tool work fine, like if we can give a argument for directory where our chromium bin file is present. 
`-c "/usr/bin/chromium"`  may be this problem will be solve.

**Comment by lauritzh** [comment]
Hi @abdulx01,

Thank you very much for your follow-up and detailed console outputs, it helped a lot! :) 

The `--no-sandbox` option was introduced recently. I would suppose there should be additional console output, in case your version would support that flag: `[+] Launching without sandbox...'`
https://github.com/lauritzh/domscan/blob/main/scan.js#L549

Does your version's help output include that flag?
```console
$ domscan

     _                                     
  __| | ___  _ __ ___  ___  ___ __ _ _ __  
 / _` |/ _ \| '_ ` _ \/ __|/ __/ _` | '_ \ 
| (_| | (_) | | | | | \__ \ (_| (_| | | | |
 \__,_|\___/|_| |_| |_|___/\___\__,_|_| |_|
             
 (C) Lauritz Holtmann, 2023
 
Options:
[...]
      --nosandbox, ---no-sandbox  Launch Chromium without sandbox
                                                      [boolean] [default: false]                                                      
```

If not, I would suggest to update to the most recent version :)     


On a side note: I noticed that I forgot to increment the version output from `domscan --version` for the `v0.0.5` - it unfortunately still prints out `v0.0.4` in the most recent version. 🙈 Sorry for that, will adjust that with the next release, for now the `---no-sandbox` option in the help output should be sufficient for you to determine whether you are using the most current version.

Please let me know, whether you have any further comments or questions!

Best regards and have a great day,

Lauritz
